;;; init-mail-test.el --- Isolated mail/privacy tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'init-mail)
(require 'nnimap)
(require 'smtpmail)

;; Never inspect a real account, vault or credential cache while testing.
(defvar mail-test-root (make-temp-file "mail-tests-" t))
(setq sanityinc/mail-vault-directory (expand-file-name "vault/" mail-test-root)
      sanityinc/mail-state-directory (expand-file-name "state/" mail-test-root)
      sanityinc/mail-imap-host "imap.example.invalid"
      sanityinc/mail-smtp-host "smtp.example.invalid")
(add-hook 'kill-emacs-hook (lambda () (delete-directory mail-test-root t)))

(defun mail-test-profile (&optional secret)
  "Return fresh synthetic test data, never a working credential."
  (append (list :version 1 :account-name "mail" :imap-host "imap.example.invalid"
                :imap-port 993 :imap-security "tls" :smtp-host "smtp.example.invalid"
                :smtp-port 587 :smtp-security "starttls" :tls-priority nil
                :email "reader@example.invalid" :login "example-user" :name "Example Reader")
          (when secret (list :password (copy-sequence "FAKE-mail-password-测试-123")))))

(ert-deftest mail-load-does-not-request-identity ()
  (should-not sanityinc/mail--configured)
  (should-not sanityinc/mail-vault--profile))

(ert-deftest mail-session-auth-never-reads-files ()
  (auth-source-forget-all-cached)
  (let ((auth-sources '("must-not-read.authinfo")) (prompts 0))
    (cl-letf (((symbol-function 'auth-source-backend-parse)
               (lambda (&rest _) (ert-fail "File credential backend accessed")))
              ((symbol-function 'read-passwd)
               (lambda (&rest _) (cl-incf prompts) "FAKE-session-password")))
      (dotimes (_ 2)
        (let ((entry (sanityinc/mail--private-connection
                      (lambda ()
                        (car (auth-source-search :host "test.invalid" :port "993"
                                                 :user "example-user" :max 1
                                                 :require '(:user :secret) :create t))))))
          (should (equal (auth-info-password entry) "FAKE-session-password"))
          (should-not (plist-get entry :save-function))))
      (should (= prompts 1))
      (should (equal auth-sources '("must-not-read.authinfo")))))
  (auth-source-forget-all-cached))

(ert-deftest mail-connection-preserves-strict-tls-and-suppresses-debugging ()
  (let ((nnimap-address sanityinc/mail-imap-host) (nnimap-stream 'plain)
        (sanityinc/mail--login "example-user") (auth-source-debug t)
        (smtpmail-debug-info t) (nnimap-record-commands t) (gnutls-verify-error nil))
    (sanityinc/mail--imap-connection
     (lambda ()
       (should (equal nnimap-user "example-user"))
       (should (eq nnimap-stream 'tls))
       (should gnutls-verify-error)
       (should-not auth-sources)
       (should-not auth-source-debug)
       (should-not smtpmail-debug-info)
       (should-not nnimap-record-commands)
       (should-not debug-on-error)
       (should-not auth-source-save-behavior)))))

(ert-deftest mail-smtp-security-is-configurable ()
  (let ((smtpmail-smtp-server sanityinc/mail-smtp-host)
        (sanityinc/mail-smtp-security 'starttls))
    (sanityinc/mail--smtp-connection
     (lambda () (should (eq smtpmail-stream-type 'starttls)) (should gnutls-verify-error)))))

(ert-deftest mail-leaves-unrelated-auth-alone ()
  (let ((nnimap-address "other.invalid") (smtpmail-smtp-server "other.invalid")
        (auth-sources '("original-source")))
    (dolist (wrapper '(sanityinc/mail--imap-connection sanityinc/mail--smtp-connection))
      (funcall wrapper (lambda () (should (equal auth-sources '("original-source"))))))))

(ert-deftest mail-lock-clears-only-account-caches ()
  (let ((sanityinc/mail-vault--profile (mail-test-profile t)) hosts)
    (cl-letf (((symbol-function 'auth-source-forget+)
               (lambda (&rest spec) (push (plist-get spec :host) hosts))))
      (sanityinc/mail-forget-passwords)
      (should-not sanityinc/mail-vault--profile)
      (should (= (length hosts) 3))
      (should (member sanityinc/mail-account-name hosts)))))

(ert-deftest mail-setup-is-offline-and-does-not-save-identity-in-method ()
  (let ((sanityinc/mail--configured nil))
    (cl-letf (((symbol-function 'sanityinc/mail--prompt-profile) #'mail-test-profile)
              ((symbol-function 'open-network-stream)
               (lambda (&rest _) (ert-fail "Setup attempted a network connection"))))
      (sanityinc/mail-setup)
      (should sanityinc/mail--configured)
      (should (= smtpmail-smtp-service 587))
      (should (eq smtpmail-stream-type 'starttls))
      (should (equal gnus-select-method '(nnnil)))
      (should (equal gnus-secondary-select-methods
                     '((nnimap "mail" (nnimap-address "imap.example.invalid")
                               (nnimap-server-port 993) (nnimap-stream tls)))))
      (should (eq nnmail-expiry-wait 'never)))))

(ert-deftest mail-rejects-plaintext-and-invalid-ports ()
  (dolist (change '((:smtp-security . "plain") (:imap-security . "network")
                    (:smtp-port . 70000) (:imap-port . 0) (:email . "invalid")
                    (:smtp-host . "https://smtp.example.invalid")))
    (should-error (sanityinc/mail-vault--validate
                   (plist-put (mail-test-profile) (car change) (cdr change))) :type 'user-error)))

(ert-deftest mail-vault-search-is-lazy-and-scoped ()
  (let ((sanityinc/mail--login "example-user") (sanityinc/mail-smtp-port 587))
    (cl-letf (((symbol-function 'sanityinc/mail-vault-enabled-p) (lambda () t))
              ((symbol-function 'sanityinc/mail-vault--unlock)
               (lambda () (ert-fail "Search decrypted without requesting the secret"))))
      (let ((result (sanityinc/mail-vault--search
                     :host (list "mail" sanityinc/mail-imap-host) :port '(993 "imaps")
                     :user "example-user" :require '(:user :secret))))
        (should (= (length result) 1))
        (should (functionp (plist-get (car result) :secret)))))))

(ert-deftest mail-vault-rejects-wrong-host-port-user-and-client-cert-queries ()
  (let ((sanityinc/mail--login "example-user"))
    (cl-letf (((symbol-function 'sanityinc/mail-vault-enabled-p) (lambda () t)))
      (dolist (spec '((:host "other.invalid" :port 993)
                      (:host "imap.example.invalid" :port 25)
                      (:host "imap.example.invalid" :port 993 :user "other-user")
                      (:host "imap.example.invalid" :port 993 :require (:key :cert))))
        (should-not (apply #'sanityinc/mail-vault--search spec))))))

(ert-deftest mail-vault-gpg-roundtrip-restart-and-no-plaintext-files ()
  (let* ((sanityinc/mail-vault-directory (expand-file-name "roundtrip/" mail-test-root))
         (sanityinc/mail-vault--profile nil)
         (profile (mail-test-profile t))
         (original-make-process (symbol-function 'make-process))
         (original-write-region (symbol-function 'write-region))
         (secret (plist-get profile :password))
         (prompts 0))
    (cl-letf (((symbol-function 'read-passwd)
               (lambda (&rest _) (cl-incf prompts) (copy-sequence "FAKE-vault-passphrase-only-for-tests")))
              ((symbol-function 'make-process)
               (lambda (&rest args)
                 (should-not (member secret (plist-get args :command)))
                 (should-not (member "FAKE-vault-passphrase-only-for-tests" (plist-get args :command)))
                 (should-not (plist-get args :buffer))
                 (should (eq (plist-get args :connection-type) 'pipe))
                 (apply original-make-process args)))
              ((symbol-function 'write-region)
               (lambda (start end &rest args)
                 (when (stringp start)
                   (should-not (string-match-p (regexp-quote secret) start))
                   (should-not (string-match-p "reader@example.invalid" start)))
                 (apply original-write-region start end args))))
      (sanityinc/mail-vault-save profile)
      (should (= prompts 1))
      (should (equal (sanityinc/mail-vault--secret) secret))
      (when-let* ((export (getenv "MAIL_VAULT_TEST_EXPORT")))
        (copy-file (sanityinc/mail-vault-file) export t))
      (sanityinc/mail-vault-lock)
      ;; Decryption must never create a plaintext temporary file.
      (cl-letf (((symbol-function 'make-temp-file)
                 (lambda (&rest _) (ert-fail "Decryption attempted a temporary file"))))
        (should (equal (plist-get (sanityinc/mail-vault-identity) :email) "reader@example.invalid"))
        (should (equal (sanityinc/mail-vault--secret) secret)))
      (should (= prompts 2))
      (let ((sanityinc/mail--login "example-user")
            (sanityinc/mail-imap-host "imap.example.invalid")
            (sanityinc/mail-smtp-host "smtp.example.invalid")
            (sanityinc/mail-imap-port 993)
            (sanityinc/mail-smtp-port 587))
        (auth-source-forget-all-cached)
        (dolist (endpoint '(("imap.example.invalid" . "993") ("smtp.example.invalid" . "587")))
          (let ((entry (sanityinc/mail--private-connection
                        (lambda ()
                          (car (auth-source-search :host (car endpoint) :port (cdr endpoint)
                                                   :user "example-user" :max 1
                                                   :require '(:user :secret) :create t))))))
            (should (equal (auth-info-password entry) secret))
            (should-not (plist-get entry :save-function))))
        (auth-source-forget-all-cached))
      (should (= prompts 2))
      (should-not (directory-files sanityinc/mail-vault-directory nil "\\`\\.account-"))
      (should-error (sanityinc/mail-vault--run nil "FAKE-wrong-passphrase") :type 'user-error))))

(ert-deftest mail-vault-disable-removes-only-ciphertext ()
  (let ((sanityinc/mail-vault-directory (expand-file-name "disable/" mail-test-root))
        (sanityinc/mail-vault--profile (mail-test-profile t)))
    (make-directory sanityinc/mail-vault-directory t)
    (let ((file-name-handler-alist nil))
      (write-region "synthetic-ciphertext" nil (sanityinc/mail-vault-file) nil 'silent))
    (write-region "preserve" nil (expand-file-name "unrelated" sanityinc/mail-vault-directory) nil 'silent)
    (sanityinc/mail-disable-persistence)
    (should-not (file-exists-p (sanityinc/mail-vault-file)))
    (should-not sanityinc/mail-vault--profile)
    (should (file-exists-p (expand-file-name "unrelated" sanityinc/mail-vault-directory)))))

;;; init-mail-test.el ends here
